using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Jewel.JPMS.Api.Migrations
{
    /// <summary>
    /// The persisted invite-composer draft: six nullable columns on BidPackages
    /// (InviteDraftSubject/Body/To/Cc/Bcc/SavedAt), saved server-side on the package so any team
    /// member can resume a half-written tender invite.
    ///
    /// HAND-CORRECTED 2026-08-16: the scaffolded version of this migration was generated against a
    /// stale JpmsContextModelSnapshot (a JpmsContextModelSnapshot.cs.new had been left beside the
    /// real one), so it tried to drop IntakeEmails/MailboxSyncStates and re-create thirty-odd
    /// tables that already exist — running it would have destroyed live data. Everything except
    /// the six genuinely new columns was deleted; the snapshot and Designer regenerated by the
    /// scaffold reflect the CURRENT model and are kept. Prod is brought level by the scoped script
    /// api/Migrations/add-bid-package-invite-draft.sql, which records this migration id in
    /// __EFMigrationsHistory so EF never tries to apply this file itself.
    /// </summary>
    public partial class AddBidPackageInviteDraft : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "InviteDraftBcc",
                table: "BidPackages",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "InviteDraftBody",
                table: "BidPackages",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "InviteDraftCc",
                table: "BidPackages",
                type: "nvarchar(2000)",
                maxLength: 2000,
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "InviteDraftSavedAt",
                table: "BidPackages",
                type: "datetimeoffset",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "InviteDraftSubject",
                table: "BidPackages",
                type: "nvarchar(512)",
                maxLength: 512,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "InviteDraftTo",
                table: "BidPackages",
                type: "nvarchar(2000)",
                maxLength: 2000,
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "InviteDraftBcc",
                table: "BidPackages");

            migrationBuilder.DropColumn(
                name: "InviteDraftBody",
                table: "BidPackages");

            migrationBuilder.DropColumn(
                name: "InviteDraftCc",
                table: "BidPackages");

            migrationBuilder.DropColumn(
                name: "InviteDraftSavedAt",
                table: "BidPackages");

            migrationBuilder.DropColumn(
                name: "InviteDraftSubject",
                table: "BidPackages");

            migrationBuilder.DropColumn(
                name: "InviteDraftTo",
                table: "BidPackages");
        }
    }
}
