using static Jewel.JPMS.Models.Ask;

namespace Jewel.JPMS.Models;

public static partial class CyberQuizQuestions
{
    private static FormQuestion[] Closing() => new[]
    {
        Choice("data_in_ai", "Data in AI tools - Which of the following should NEVER be pasted into an AI tool unless it is an approved enterprise AI service?", Required,
            new[] { "General questions about UK weather",
                "Client names, financial data, contracts, passwords, or other confidential business information",
                "Public news articles", "A weather forecast for London" }),
        Choice("ai_outputs", "Using AI outputs - You've used an approved AI tool to draft a client email. What should you do before sending it?", Required,
            new[] { "Send it straight away - the AI is reliable",
                "Review, fact-check and edit it yourself - you are responsible for the final content",
                "Forward it to Jeremy to send instead", "Send it and apologise later if anything is wrong" }),
        Choice("ai_best_practice", "Perplexity / AI tool best practice - When using Perplexity or another approved AI tool for JBB work, what should you do?", Required,
            new[] { "Use it for general research and drafting, never enter confidential JBB data (client names, contracts, financials, passwords), and review all outputs before using them",
                "Use whichever account is faster to sign into",
                "Share your AI chat link publicly so colleagues can see it", "Trust the AI's answer without checking it" }),
        Choice("monitoring", "Monitoring - Which statement best describes Jewel Bespoke Build's monitoring of work activity?", Required,
            new[] { "Jewel Bespoke Build uses monitoring and process discovery tools to understand workflows and ensure compliance, with appropriate notice to staff",
                "Monitoring is only used for senior staff", "Only personal email is monitored", "Jewel Bespoke Build does not monitor anything" }),
        Choice("individual_monitoring", "Individual monitoring - If Jewel Bespoke Build reviews individual activity logs, when would this normally happen?", Required,
            new[] { "Randomly, just to spy on staff",
                "If there is a genuine compliance, security, performance or HR reason - and always within data protection rules",
                "Only when senior management wants to embarrass someone", "Never, under any circumstances" }),
        Choice("shadow_it", "Shadow IT - You discover a great new web tool that would speed up your work. What should you do?", Required,
            new[] { "Just start using it for JBB work - it's quicker than asking",
                "Ask Jeremy or IT to approve it before using it for any JBB work or data",
                "Use it for personal projects only", "Install it on your work laptop and tell people about it" }),
        Choice("storing_documents", "Storing work documents - Where should JBB work documents be stored?", Required,
            new[] { "On personal cloud accounts (personal Dropbox, Google Drive, iCloud) for easy access",
                "In JBB-approved Microsoft 365 locations (OneDrive for Business, SharePoint, Teams) only",
                "On a USB stick at home", "Wherever is most convenient" }),
        Choice("lost_device", "Lost or stolen device - Your JBB work laptop or phone is lost or stolen. What should you do first?", Required,
            new[] { "Wait a few days in case it turns up",
                "Report it immediately to Jeremy/IT so the device can be locked, wiped and access revoked",
                "Try to find it yourself before telling anyone", "Buy a replacement and say nothing" }),
        Choice("copilot_contracts", "Microsoft 365 Copilot with external data - You want to use Copilot to summarise a client contract. What is the correct approach?", Required,
            new[] { "Upload the contract to a free public AI website to save time",
                "Use Microsoft 365 Copilot or another approved enterprise AI tool with the document, keeping the data within Jewel Bespoke Build's tenant",
                "Email the contract to your personal AI account so you can work on it at home",
                "Ask a colleague to send it to their personal ChatGPT account" }),
        Choice("reporting_concerns", "Reporting concerns - You think a colleague may be misusing IT systems, sharing data improperly, or ignoring cyber rules. What should you do?", Required,
            new[] { "Confront the colleague yourself and threaten to report them", "Ignore it - it's not your problem",
                "Report your concern confidentially to Jeremy or Nigel so it can be looked into properly",
                "Post about it on social media or in a group chat" }),
        Choice("screen_lock", "Clean desk and screen lock - You are leaving your desk or van to attend a meeting or site visit. What should you do?", Required,
            new[] { "Leave the laptop open and unlocked so it's quick to resume",
                "Lock the screen (Windows+L / Ctrl+Cmd+Q), and secure any paperwork containing client or staff data",
                "Ask a colleague to keep an eye on your laptop instead of locking it",
                "Leave the laptop on a site desk - everyone there is trustworthy" }),
        Choice("public_wifi", "Public Wi-Fi and working away from the office - You are working from a cafe, hotel or client site and need to access JBB systems. What should you do?", Required,
            new[] { "Connect to any free public Wi-Fi - it's fine as long as the network has a name",
                "Use your phone's secure mobile hotspot (4G/5G) or a known trusted network, and ensure your VPN is on before accessing JBB systems",
                "Ask the venue staff for their Wi-Fi password and assume it's safe",
                "Use a personal device on home Wi-Fi - no VPN needed, your home network is private" }),
        Choice("data_breach", "Data breach (GDPR) - You accidentally emailed a spreadsheet containing client or staff personal data to the wrong person, or you've lost a JBB phone/laptop. What should you do?", Required,
            new[] { "Do nothing and hope it isn't noticed",
                "Report it to Jeremy and IT immediately so it can be assessed and, if needed, reported to the ICO within 72 hours under GDPR",
                "Try to recall the email yourself and tell no one - it's just one email", "Wait until the weekly meeting to mention it" }),
        Choice("deepfakes", "AI deepfakes and voice cloning - You get a phone call, voicemail or video message that sounds like Nigel or Jeremy urgently asking you to make a payment, share login details or buy gift cards. What should you do?", Required,
            new[] { "Do as they say straight away - it sounds just like them",
                "Stop. Assume it could be an AI voice/video deepfake, hang up, and verify by calling Nigel or Jeremy back on their known number before doing anything",
                "Forward the message to a colleague to deal with", "Make the payment but only if it is under £500" }),
        Choice("usb_sticks", "USB and removable media - You find an unlabelled USB stick in the office, on site or in a vehicle. What should you do?", Required,
            new[] { "Plug it into your laptop to see what's on it and find the owner",
                "Do not plug it in. Hand it to IT/Jeremy so it can be safely checked or destroyed - unknown USBs can carry malware",
                "Take it home and check it on your personal PC", "Leave it on someone else's desk so they deal with it" })
    };
}
