"""Step 2b of the bulk load: the guarded T-SQL that registers the uploaded files.

One batch, one transaction. Folders are resolved by name under their parent (an existing
folder is reused, a missing one created), drawings are skipped when the project already has
that code, and every revision is guarded on its BlobRef so the script can be re-run.
"""
from dataclasses import dataclass, field

APPROVED, UNAPPROVED, ARCHIVED = 1, 0, 2
PRODUCT_VERSION_NOTE = "-- Generated by scripts/bulk-load-drawings — safe to re-run."


def literal(value: str | None) -> str:
    if value is None or value == "":
        return "NULL"
    return "N'" + value.replace("'", "''") + "'"


@dataclass
class FolderPlan:
    variable: str
    name: str
    parent_variable: str | None
    new_id: str


@dataclass
class RevisionPlan:
    revision_id: str
    label: str
    file_name: str
    blob_ref: str
    content_type: str
    size_bytes: int
    status: int


@dataclass
class DrawingPlan:
    drawing_id: str
    code: str
    title: str
    folder_variable: str | None
    revisions: list[RevisionPlan] = field(default_factory=list)


def folder_block(project_id: str, folder: FolderPlan) -> str:
    parent = folder.parent_variable or "NULL"
    parent_test = "IS NULL" if folder.parent_variable is None else f"= {folder.parent_variable}"
    return f"""
DECLARE {folder.variable} nvarchar(64);
SELECT {folder.variable} = DrawingFolderId FROM DrawingFolders
 WHERE ProjectId = {literal(project_id)} AND ParentDrawingFolderId {parent_test} AND LOWER(Name) = LOWER({literal(folder.name)});
IF {folder.variable} IS NULL
BEGIN
    SET {folder.variable} = {literal(folder.new_id)};
    INSERT INTO DrawingFolders (DrawingFolderId, ProjectId, Name, CreatedAt, ParentDrawingFolderId)
    VALUES ({folder.variable}, {literal(project_id)}, {literal(folder.name)}, SYSDATETIMEOFFSET(), {parent});
END;"""


def revision_insert(drawing_id: str, revision: RevisionPlan, issued_by: str, approved_by: str) -> str:
    is_approved = revision.status == APPROVED
    is_archived = revision.status == ARCHIVED
    return f"""
    IF NOT EXISTS (SELECT 1 FROM DrawingRevisions WHERE BlobRef = {literal(revision.blob_ref)})
    INSERT INTO DrawingRevisions (DrawingRevisionId, DrawingId, RevisionLabel, FileName, IssuedByEmail, ReceivedAt,
        SupersededAt, IsAmbiguous, ViewCount, ApprovalStatus, BlobRef, ContentType, FileSizeBytes, ApprovedByEmail, ApprovedAt)
    VALUES ({literal(revision.revision_id)}, {literal(drawing_id)}, {literal(revision.label) if revision.label else "N''"},
        {literal(revision.file_name)}, {literal(issued_by) if issued_by else "N''"}, SYSDATETIMEOFFSET(),
        {"SYSDATETIMEOFFSET()" if is_archived else "NULL"}, 0, 0, {revision.status}, {literal(revision.blob_ref)},
        {literal(revision.content_type)}, {revision.size_bytes},
        {literal(approved_by) if is_approved else "NULL"}, {"SYSDATETIMEOFFSET()" if is_approved else "NULL"});"""


def drawing_block(project_id: str, drawing: DrawingPlan, issued_by: str, approved_by: str) -> str:
    approved = next((revision for revision in drawing.revisions if revision.status == APPROVED), None)
    approved_label = literal(approved.label) if approved and approved.label else "NULL"
    folder = drawing.folder_variable or "NULL"
    revisions = "".join(revision_insert(drawing.drawing_id, revision, issued_by, approved_by) for revision in drawing.revisions)
    if drawing.code:
        guard = f"""IF EXISTS (SELECT 1 FROM Drawings WHERE ProjectId = {literal(project_id)} AND LOWER(DrawingCode) = LOWER({literal(drawing.code)}))
BEGIN
    PRINT 'Skipped {drawing.code.replace("'", "''")} — the project already has a drawing with this code.';
END
ELSE"""
    else:
        guard = f"IF NOT EXISTS (SELECT 1 FROM Drawings WHERE DrawingId = {literal(drawing.drawing_id)})"
    return f"""
{guard}
BEGIN
    INSERT INTO Drawings (DrawingId, ProjectId, DrawingCode, Title, CurrentApprovedRevisionLabel, CreatedAt, DrawingFolderId)
    VALUES ({literal(drawing.drawing_id)}, {literal(project_id)}, {literal(drawing.code) if drawing.code else "N''"},
        {literal(drawing.title) if drawing.title else "N''"}, {approved_label}, SYSDATETIMEOFFSET(), {folder});{revisions}
END;"""


def render(project_id: str, folders: list[FolderPlan], drawings: list[DrawingPlan], issued_by: str, approved_by: str) -> str:
    parts = [PRODUCT_VERSION_NOTE, "SET XACT_ABORT ON;", "BEGIN TRANSACTION;",
             f"IF NOT EXISTS (SELECT 1 FROM Projects WHERE ProjectId = {literal(project_id)}) THROW 50000, 'Project not found.', 1;"]
    parts += [folder_block(project_id, folder) for folder in folders]
    parts += [drawing_block(project_id, drawing, issued_by, approved_by) for drawing in drawings]
    parts += ["", "COMMIT;", "GO", ""]
    return "\n".join(parts)
