using Jewel.JPMS.Api.Cqrs;
using Jewel.JPMS.Api.Data;
using Jewel.JPMS.Api.Data.Entities;
using Jewel.JPMS.Contracts.Subcontractors;
using Jewel.JPMS.Models;
using Microsoft.EntityFrameworkCore;

namespace Jewel.JPMS.Api.Features.Subcontractors.Commands;

/// <summary>
/// Versioning writer: the new document becomes the current version of its Kind and every
/// previously-current sibling is stamped SupersededAt (kept for audit, still downloadable).
/// Kind matching is case-insensitive so "insurance" and "Insurance" don't fork histories.
/// </summary>
public sealed class AddComplianceDocumentVersionHandler
    : ICommandHandler<AddComplianceDocumentVersion, ComplianceDocument>
{
    private readonly JpmsContext context;

    public AddComplianceDocumentVersionHandler(JpmsContext context) { this.context = context; }

    public async Task<ComplianceDocument> HandleAsync(AddComplianceDocumentVersion command, CancellationToken cancellationToken)
    {
        var now = DateTimeOffset.UtcNow;

        var siblings = await context.ComplianceDocuments
            .Where(row => row.SubcontractorId == command.SubcontractorId && row.Kind.ToLower() == command.Kind.ToLower())
            .ToListAsync(cancellationToken);

        foreach (var sibling in siblings.Where(row => row.SupersededAt == null))
            sibling.SupersededAt = now;

        var entity = new ComplianceDocumentEntity
        {
            // Pre-generated by the upload endpoint so the row id matches the blob path segment.
            ComplianceDocumentId = command.ComplianceDocumentId,
            SubcontractorId = command.SubcontractorId,
            Kind = command.Kind,
            FileName = command.FileName,
            ExpiresAt = command.ExpiresAt,
            UploadedAt = now,
            BlobPath = command.BlobPath,
            ContentType = command.ContentType,
            FileSize = command.FileSize,
            Version = siblings.Count == 0 ? 1 : siblings.Max(row => row.Version) + 1
        };
        context.ComplianceDocuments.Add(entity);
        await context.SaveChangesAsync(cancellationToken);
        return entity.ToModel();
    }
}
