namespace Jewel.JPMS.Models;

/// <summary>
/// The items of the framework's current version — Katy-Louise Hicks's simplified workbook of
/// 15 Sep 2026, item for item (165 rows). Sections 1, 3–7 and 11 are the 27 Aug list unchanged;
/// temporary works is one line, working at heights nine, traffic management five, fire and
/// emergency six. Spelling corrected, wording hers.
/// </summary>
public static class HsAuditTemplateItems
{
    public static readonly IReadOnlyList<HsAuditTemplateItem> Current = new HsAuditTemplateItem[]
    {
        // 1 Documentation
        new("1.01", 1, "Health & Safety Plan"),
        new("1.02", 1, "General Risk Assessments"),
        new("1.03", 1, "Method Statements"),
        new("1.04", 1, "Method Statement Review Checklist"),
        new("1.05", 1, "CoSHH Assessments"),
        new("1.06", 1, "Other Risk Assessments"),
        new("1.07", 1, "Lifting Plans"),
        new("1.08", 1, "Briefing Registers"),
        new("1.09", 1, "Test Certificates"),
        new("1.10", 1, "Inspection Records"),
        new("1.11", 1, "Permits to Work"),
        new("1.12", 1, "Certificates of Competence"),
        new("1.13", 1, "Induction Training"),
        new("1.14", 1, "Toolbox Talks"),
        new("1.15", 1, "Safety Advisor Inspection/ Audit"),
        new("1.16", 1, "Site Management Safety Inspections"),
        new("1.17", 1, "Contractor Safety Inspections"),
        new("1.18", 1, "Emergency Procedures"),
        new("1.19", 1, "Visitors/ Contracts Register (PC Only)"),
        new("1.20", 1, "PPI Issue/ Held Records"),
        new("1.21", 1, "Vibration Exposure Records"),
        new("1.22", 1, "Isolation Procedures"),
        new("1.23", 1, "Daily Briefing Sheets"),
        new("1.24", 1, "Health Assessment Questionnaire"),
        new("1.25", 1, "Accident Records"),
        // 2 Temporary Works
        new("2.01", 2, "Where temporary works are present, designs, appointments, permits, registers, inspections, maintenance and handover controls are in place"),
        // 3 Notices & Posters
        new("3.01", 3, "F10 - HSE Notification"),
        new("3.02", 3, "Health & Safety Law Poster"),
        new("3.03", 3, "Traffic Management Plan"),
        new("3.04", 3, "Fire Plan Layout"),
        new("3.05", 3, "First Aid Notices/ Signs"),
        new("3.06", 3, "Other Notices and Posters"),
        // 4 Specific Training
        new("4.01", 4, "Manager/ Supervisor Training"),
        new("4.02", 4, "Lifting Operations"),
        new("4.03", 4, "Mobile Plant Operations"),
        new("4.04", 4, "Temporary Works"),
        new("4.05", 4, "Traffic Management"),
        new("4.06", 4, "Access Equipment"),
        new("4.07", 4, "Confined Spaces"),
        new("4.08", 4, "Abrasive Wheels"),
        new("4.09", 4, "Harness"),
        new("4.10", 4, "First Aid Training"),
        new("4.11", 4, "Fire Safety Training"),
        new("4.12", 4, "Asbestos Awareness/ Management"),
        new("4.13", 4, "NRSWA"),
        new("4.14", 4, "CAT & Genny"),
        new("4.15", 4, "Face Fit Testing"),
        // 5 General
        new("5.01", 5, "General Housekeeping"),
        new("5.02", 5, "Site Access/ Egress"),
        new("5.03", 5, "Perimeter Fencing/ Hoarding"),
        new("5.04", 5, "Internal Exclusion Zones"),
        new("5.05", 5, "General Site Signage"),
        new("5.06", 5, "Protection of the Public"),
        new("5.07", 5, "Storage of Materials"),
        new("5.08", 5, "Storage of Tools"),
        new("5.09", 5, "CoSHH - Handling/ Storage"),
        new("5.10", 5, "Flammable Gas & Liquid Storage/ Use"),
        new("5.11", 5, "Lifting Equipment"),
        new("5.12", 5, "Mobile Work Equipment"),
        new("5.13", 5, "Other Work Equipment"),
        new("5.14", 5, "Electrical Systems"),
        new("5.15", 5, "Underground Services"),
        new("5.16", 5, "Overhead Services/ Obstacles"),
        new("5.17", 5, "Excavation Safety"),
        new("5.18", 5, "Ponds, Lagoons, other Watercourses"),
        new("5.19", 5, "Floor/ Ground Conditions/ Voids"),
        new("5.20", 5, "Lighting - Access/ Task"),
        new("5.21", 5, "Cables/ Hose Management"),
        new("5.22", 5, "Personal Protective Equipment"),
        new("5.23", 5, "Dust and Fume Control"),
        new("5.24", 5, "Control of Noise"),
        new("5.25", 5, "Control of Vibration"),
        new("5.26", 5, "Stockpile and Tips"),
        new("5.27", 5, "Guarding"),
        new("5.28", 5, "Protection of Protruding Items"),
        new("5.29", 5, "Restricted Areas"),
        new("5.30", 5, "Fixtures and Fittings"),
        new("5.31", 5, "Asbestos Containing Materials"),
        new("5.32", 5, "Ventilation/ Extraction"),
        // 6 Environment
        new("6.01", 6, "Permits & Licences"),
        new("6.02", 6, "Waste Management"),
        new("6.03", 6, "Avoidance of Pollution & Nuisance"),
        new("6.04", 6, "Fuel/ Oil Storage/ Bunds"),
        new("6.05", 6, "Spill Kits Available"),
        new("6.06", 6, "Emissions and Discharges"),
        new("6.07", 6, "External Roads Clean and Unaffected"),
        new("6.08", 6, "Site Litter Free"),
        new("6.09", 6, "Flora, Fauna, Wildlife Protection"),
        new("6.10", 6, "Contaminated Land Control"),
        new("6.11", 6, "General Appearance of the Site"),
        // 7 Work Activities
        new("7.01", 7, "Manual Handling"),
        new("7.02", 7, "Mechanical Handling (not crane)"),
        new("7.03", 7, "Crane Operations"),
        new("7.04", 7, "Loading/ Unloading of Materials"),
        new("7.05", 7, "Excavating/ Earthworks"),
        new("7.06", 7, "Plant & Machinery Operations"),
        new("7.07", 7, "Demolition/ Strip Out"),
        new("7.08", 7, "Crushing/ Screening/ Batching Operations"),
        new("7.09", 7, "Steel Framework"),
        new("7.10", 7, "Falsework/ Formwork"),
        new("7.11", 7, "Steel Fixing"),
        new("7.12", 7, "Concreting Operations"),
        new("7.13", 7, "Asbestos Management"),
        new("7.14", 7, "Welding/ Cutting/ Grinding Operations"),
        new("7.15", 7, "Drylining & Plastering"),
        new("7.16", 7, "Working Over or Near Water"),
        new("7.17", 7, "Confined Spaces"),
        new("7.18", 7, "Lone Working"),
        new("7.19", 7, "Glass & Glazing"),
        new("7.20", 7, "Paving (Blocks, Slabs, Tarmac, etc)"),
        new("7.21", 7, "Piling Operations"),
        new("7.22", 7, "Electrical Works"),
        new("7.23", 7, "Drainage Works"),
        new("7.24", 7, "Gas Works (inc. Plumbing & Heating)"),
        new("7.25", 7, "Brickwork and Blockwork"),
        new("7.26", 7, "Carpentry"),
        new("7.27", 7, "Cladding (incl. Fitting of Roller Doors)"),
        new("7.28", 7, "Fencing Operations"),
        new("7.29", 7, "Maintenance Activities"),
        new("7.30", 7, "Roofwork"),
        new("7.31", 7, "Decorations (Internal & External)"),
        new("7.32", 7, "Stonework"),
        new("7.33", 7, "Internal Fit-Out"),
        new("7.34", 7, "Ceilings"),
        new("7.35", 7, "Landscaping Operations"),
        new("7.36", 7, "Temporary Works"),
        new("7.37", 7, "Waterproofing"),
        new("7.38", 7, "Mechanical Works"),
        new("7.39", 7, "Water Treatment Works"),
        new("7.40", 7, "Installation of Pre Cast Elements"),
        new("7.41", 7, "Production Activities"),
        new("7.42", 7, "General Labouring"),
        new("7.43", 7, "Installation of Insulation Materials"),
        new("7.44", 7, "Cooking & Other Kitchen Activities"),
        new("7.45", 7, "Flooring (Tiles, Carpets, Screed, etc.)"),
        new("7.46", 7, "Installation of Fire Safety Systems"),
        new("7.47", 7, "Membrane Installation (Gas/ Water)"),
        new("7.48", 7, "Lift Installation/ Maintenance"),
        new("7.49", 7, "Underpinning Work"),
        new("7.50", 7, "UXO Surveys/ Removal"),
        new("7.51", 7, "Shotblasting/ Sandblasting"),
        // 8 Working at Heights
        new("8.01", 8, "Scaffolding"),
        new("8.02", 8, "MEWPs"),
        new("8.03", 8, "Mobile Towers/ Podiums"),
        new("8.04", 8, "Ladders/ Stepladders"),
        new("8.05", 8, "Hop Ups/ Other Platforms"),
        new("8.06", 8, "Edge/ Opening Protection"),
        new("8.07", 8, "Safety Nets/ Air Bags/ Soft Landing Systems / Fall Restraint/ Fall Arrest"),
        new("8.08", 8, "Fragile Materials"),
        new("8.09", 8, "Falling Objects"),
        // 9 Traffic Management
        new("9.01", 9, "Vehicle routes, delivery arrangements and loading/unloading areas are planned and communicated."),
        new("9.02", 9, "Pedestrians and vehicles are segregated where reasonably practicable."),
        new("9.03", 9, "Reversing is avoided or controlled through layout, banksmen and exclusion zones."),
        new("9.04", 9, "Speed limits, crossing points, signs, barriers, parking and site access are controlled."),
        new("9.05", 9, "Drivers, visitors and delivery personnel receive relevant instructions."),
        // 10 Fire & Emergency
        new("10.01", 10, "First Aid Arrangements"),
        new("10.02", 10, "Fire Points, alarms, fire prevention, escape routes, emergency lighting & assembly points"),
        new("10.03", 10, "Control of Smoking / vaping"),
        new("10.04", 10, "Temporary Accommodation & temporary coverings"),
        new("10.05", 10, "Heaters and Cooking Appliances"),
        new("10.06", 10, "Other Emergency Procedures"),
        // 11 Offices and Welfare
        new("11.01", 11, "Canteen Facilities"),
        new("11.02", 11, "Toilets & Washing Facilities"),
        new("11.03", 11, "Drying/ Changing Rooms"),
        new("11.04", 11, "Offices"),
    };
}
